### ISSUE TITLE
怎么把初始化和刷新数据分开写呢？

### ISSUE THREAD

**Issue by zohar-soul** [ssseasonnn/Yaksa#3]
求问
看demo只能每次刷新数据或增加数据都那么写呢
也就是说初始化recyclerview adapter和更新数据不能分开吗

**Comment by ssseasonnn** [comment]
初始化直接 recyclerview.linear{} 就行了

**Comment by zohar-soul** [comment]
对呀 我的意思是
现在demo中的写法 绑定数据是每次都要设置一次的啊
而不是设置好之后，notify就可以了呢

**Comment by ssseasonnn** [comment]
现在不需要notify，只需要你改变数据源，这边就会自动更新，你可以理解成数据驱动

**Comment by ssseasonnn** [comment]
你用renderItems(dataSource.list)的时候已经绑定了数据源

**Comment by ssseasonnn** [comment]
和Item没有关系

**Comment by zohar-soul** [comment]
对啊 
那么为什么 我改变renderItems(list) 所绑定的
list数据的话 列表不会发生改变呢？

**Comment by ssseasonnn** [comment]
你写错了吧😂

**Comment by ssseasonnn** [comment]
我懂你的意思了，你是想说把绑定的数据换成livedata这样的只要数据变了，就会自动刷新是吧，不用再重新执行一次 recyclerview.linear{ renderItems{}} 对吧

**Comment by ssseasonnn** [comment]
没毛病老铁，我改一下

**Comment by zohar-soul** [comment]
是的。。。我就是这个意思
数据直接驱动ui
没必要每次都设置一次呀
虽然你有缓存不会重新创建
但是初始化和数据改变都在一起也不好看呀
尤其是，
recyclerview.linear{ renderItems{}}
里面每次都有绑定xml之类的

**Comment by ssseasonnn** [comment]
可以了老铁，新版已经发布了

**Comment by zohar-soul** [comment]
非常感谢！
